/**
 * Entity package containing all JPA entity classes for the LanhCare health tracking system.
 * 
 * <p>This package follows the Code-First approach where entities are defined in Java
 * and the database schema is auto-generated by JPA/Hibernate.</p>
 * 
 * <h2>Main Entities:</h2>
 * <ul>
 *   <li>{@link com.lanhcare.entity.Account} - User accounts and authentication</li>
 *   <li>{@link com.lanhcare.entity.UserHealthProfile} - User health information and metrics</li>
 *   <li>{@link com.lanhcare.entity.FoodItem} - Food database and nutritional information</li>
 *   <li>{@link com.lanhcare.entity.MealLog} - User meal tracking records</li>
 *   <li>{@link com.lanhcare.entity.ICD11Code} - International disease classification codes</li>
 *   <li>{@link com.lanhcare.entity.Hospital} - Medical facilities database</li>
 *   <li>{@link com.lanhcare.entity.ServicePlan} - Subscription plans</li>
 * </ul>
 * 
 * @author LanhCare Team
 * @version 1.0
 */
package com.lanhcare.entity;
